<a href="https://colab.research.google.com/github/AlexanderG40/Data-Science/blob/main/Week2_Assignment_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a NumPy program to reshape this 1D array [1 2 3 4 5 6] into a 2D array with 2 rows.

In [1]:
# Code here
import numpy as np
# here we added our array given
array = np.array([1, 2, 3, 4, 5, 6])
# here is where we reshape our array into 2D using 2 rows and 3 columns
reshaped = array.reshape(2,3)
# we print our new array in 2d
print(reshaped)

[[1 2 3]
 [4 5 6]]


Write a NumPy program to perform matrix multiplication between a 3x3 matrix and a 3x2 matrix

In [2]:
# Code here
import numpy as np
# here is the start of our first array which is a 3x3 3 rows, 3 columns
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# our second array
array2 = np.array([[1, 2,],
                   [3, 4],
                   [5, 6]])
# we use the np.dot as that is what multiply our two matrixes
multiply = np.dot(array1, array2)
#here we print our result that we get
print(multiply)

[[ 22  28]
 [ 49  64]
 [ 76 100]]


Write a NumPy program to find the most frequent value and the number of times it occured in the array


[

    [1, 2, 3, 2, 1],
    [4, 2, 5, 2, 6],
    [2, 1, 2, 3, 2],
    [7, 2, 8, 2, 9]  
 ]

In [9]:
# Code here
import numpy as np

# use the array given to us
data = np.array([
   [1, 2, 3, 2, 1],
   [4, 2, 5, 2, 6],
   [2, 1, 2, 3, 2],
   [7, 2, 8, 2, 9]
])

# here we find all the numbers and then it counts all the numbers to see which one appears more and more
# using np.unique it looks for all the numbers and if we were to print even though two is the most frequent it would only print one in the output
# https://www.geeksforgeeks.org/python-numpy-np-unique-method/
# https://www.geeksforgeeks.org/numpy-argmax-python/
numbers, num_count = np.unique(data, return_counts=True)
# here we set up the function to handle its numbers count
most_frequent = numbers[np.argmax(num_count)]
# here we set up to see how many times our most frequent value appears in our array
value_frequency = num_count[np.argmax(num_count)]

print(f"The most frequent number is: {most_frequent}, with a total frequency of: {value_frequency}")

The most frequent number is: 2, with a total frequency of: 9


Given a NumPy array representing a dataset with missing values, write a program to replace all the missing values (NaNs) with the mean of the respective column.

[  [ 1.  2. nan  4.  5.],

 [ 6. nan  8.  9. 10.],

 [11. 12. 13. nan 15.],

 [16. 17. nan 19. 20.],

 [nan 22. 23. 24. 25.]  ]

In [8]:
# Code here
import numpy as np

#we add the data given to us
data = np.array([
    [1, 2, np.nan, 4, 5],

    [6, np.nan, 8, 9, 10],

    [11, 12, 13, np.nan, 15],

    [16, 17, np.nan, 19, 20],

    [np.nan, 22, 23, 24, 25]
])

# here we make it so that the nan pretty much does not exists/ ignores it and replaces with mean
# here is a little bit of how it works, np.where "where" nan replaces the Nan with the means
# np.isnan checks for the anywhere where there is a nan if it is true it checks
# np.nanmean calculates the mean
# resources used:
# https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html
# https://www.geeksforgeeks.org/numpy-mean-in-python/
# https://numpy.org/doc/stable/reference/generated/numpy.where.html
# https://www.geeksforgeeks.org/numpy-isnan-python/
data = np.where(np.isnan(data), np.nanmean(data, axis=0), data)

print(data)

[[ 1.          2.         14.66666667  4.          5.        ]
 [ 6.         13.25        8.          9.         10.        ]
 [11.         12.         13.         14.         15.        ]
 [16.         17.         14.66666667 19.         20.        ]
 [ 8.5        22.         23.         24.         25.        ]]


Write a program that takes a NumPy array representing a dataset with a column of dates and create a new column extracting the month of each date.

np.array([

    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550)
]

In [7]:
# Code here
import numpy as np
# we also import datetime unless we want to use it doing datetime64 but thats a bit more technical and advanced
from datetime import datetime
# here we import our data that is given to us
data = np.array([
    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550)
])

# we extract only the dates from the array and ignore everything else
dates = data[:, 0]

# we use the np.array to extract the month using our datetime we imported
# https://www.geeksforgeeks.org/python-datetime-strptime-function/
months = np.array([datetime.strptime(date, '%Y-%m-%d').month for date in dates])

# we use the numpy column_stack to stack the new columns of dates next to our random numbers
# https://www.geeksforgeeks.org/numpy-column_stack-in-python/

new_column = np.column_stack((data, months))

print(new_column)




[['2024-01-15' '10' '100' '1']
 ['2024-02-28' '15' '150' '2']
 ['2024-03-10' '20' '200' '3']
 ['2024-04-22' '25' '250' '4']
 ['2024-05-05' '30' '300' '5']
 ['2024-06-18' '35' '350' '6']
 ['2024-07-30' '40' '400' '7']
 ['2024-08-12' '45' '450' '8']
 ['2024-09-25' '50' '500' '9']
 ['2024-10-07' '55' '550' '10']]
